#!/bin/sh /etc/rc.common

START=99
USE_PROCD=1

start_service() {
    local user="gitea"
    chown -R $user:$user "/usr/bin/gitea"

    procd_open_instance
    procd_set_param command /usr/bin/gitea web
    procd_set_param user "$user"
    procd_set_param respawn
    procd_close_instance
}

stop_service() {
    procd_close_instance
}

start() {
    start_service
}

stop() {
    procd_kill gitea
}

